### ISSUE TITLE
Bar button

### ISSUE THREAD

**Issue by Manueldjz** [zsy78191/XXXRoundMenuButton#1]
is possible to add this effect in a bar button item?

**Comment by zsy78191** [comment]
good idea, I think it is not very difficult，but I need an animation demo to make it.

you know, bar button can be make by custom UIView, so you can try use it ,and make the RoundMenu background color clearColor. good luck

**Comment by zsy78191** [comment]
OK , it can't use for UIBarButtonItem . I will find a way to use it for UIBarButtonItem. thx

**Comment by Manueldjz** [comment]
Thanks buddy
