### ISSUE TITLE
How to opened button with load image ?

### ISSUE THREAD

**Issue by IOSDeveloperProgrammer** [zsy78191/XXXRoundMenuButton#12]
@zsy78191  Thanks ! I changed Action button. Finally got the solution.

**Comment by zsy78191** [comment]
（：

**Comment by IOSDeveloperProgrammer** [comment]
@zsy78191  How to add background image of the circle view and title instead of icon image.I am using swift3 . please guid me

**Comment by zsy78191** [comment]
In XXXRoundMenuButton/Views/XXXRoundMenuButton.m   Line 441 
You can see the UIButton code, you can change it only show title.

Line 487 
The drawInRect function , you can draw the background image. Or  remove this, add a UIImageView instead.

**Comment by IOSDeveloperProgrammer** [comment]
@zsy78191 Thanks ! I will check and let you know. & Here, It's not default image. I need to display server image.

**Comment by IOSDeveloperProgrammer** [comment]
@zsy78191 As you said, I added code here check below
`- (void)drawRect:(CGRect)rect
{
    //// Color Declarations
    UIImage *bgImage = [UIImage imageNamed:@"status"];
 // Oval Drawing
    UIBezierPath* ovalPath = [UIBezierPath bezierPathWithOvalInRect: rect];
//    [color setFill];
    [ovalPath fill];
}
`
 I tried to add UIImage into circle view bg image. In this method changed color not add image. please help me. in

**Comment by zsy78191** [comment]
I think use UIImageView maybe more easier
you can delete ovalPath , so background will be nothing . when init, add a UIImageView as subview for circle view and set image as background.

if you want to use CoreGraphic code, I have some code you can refer
```mm
 - (void)drawCanvas1WithFrame: (CGRect)frame
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();


    //// Image Declarations
    UIImage* _14 = [UIImage imageNamed: @"_14.png"];

    //// Picture Drawing
    CGRect pictureRect = CGRectMake(CGRectGetMinX(frame) + floor((frame.size.width - 39) * 0.50820 + 0.5), CGRectGetMinY(frame) + floor((frame.size.height - 38) * 0.50000 + 0.5), 39, 38);
    UIBezierPath* picturePath = [UIBezierPath bezierPathWithRect: pictureRect];
    CGContextSaveGState(context);
    [picturePath addClip];
    CGContextTranslateCTM(context, floor(CGRectGetMinX(pictureRect) + 0.5), floor(CGRectGetMinY(pictureRect) + 0.5));
    CGContextScaleCTM(context, 1, -1);
    CGContextTranslateCTM(context, 0, -_14.size.height);
    CGContextDrawImage(context, CGRectMake(0, 0, _14.size.width, _14.size.height), _14.CGImage);
    CGContextRestoreGState(context);
}
```

**Comment by IOSDeveloperProgrammer** [comment]
@zsy78191  Sorry, background showing nothing if i commented and add image as you said to me. it showing nothing sir.
``- (void)drawRect:(CGRect)rect
{
   //// Image Declarations
    UIImage* imag = [UIImage imageNamed: @"status"];
}
`` 

I want to add bgimage instead of color. not button icon sir.
![screen shot 2017-10-24 at 3 40 58 pm](https://user-images.githubusercontent.com/20769065/31937406-ebf62e26-b8d1-11e7-958d-23dce1c925fb.png)

**Comment by IOSDeveloperProgrammer** [comment]
@zsy78191  finally got it. added image in background. Thanks for supported

**Comment by zsy78191** [comment]
Well,  (:
