### ISSUE TITLE
Share button on all app with Secret Project effect

### ISSUE THREAD

**Issue by Rufy86** [zsy78191/XXXRoundMenuButton#16]
Hi,
I've a tab bar-based app and I would like to show the button on all app. How can I do it? Furthermore, I would like to add the button behind the tab bar, so when the button expands after the click, the effect is like shown in Secret Project:https://dribbble.com/shots/1928064-Secret-Project. How can I do it?

Thank you

**Comment by zsy78191** [comment]
You should add this button at [UIApplication sharedApplication].keyWindow.
