### ISSUE TITLE
disable a subbutton

### ISSUE THREAD

**Issue by Rufy86** [zsy78191/XXXRoundMenuButton#18]
I've this button with 4 sub-button. I would like that one of this 4 sub button is disabled and get enabled if it is in some situation. e.g the share button,I would like be disabled at start, but when appear a detail to share this button become enabled.

is it possible? How?

**Comment by zsy78191** [comment]
New at 2019.02.25
use -(void)setButtonEnable:(BOOL)enable atIndex:(NSUInteger)index; can config button with RoundMenu.
