### ISSUE TITLE
Swift help

### ISSUE THREAD

**Issue by ttrushin** [zsy78191/XXXRoundMenuButton#2]
Hi, I love the look of this!  Could you please add some instructions for how to use this in a Swift-based project?  I'd really appreciate it!

**Comment by DeliciousRaspberryPi** [comment]
Try adding the XXXRoundMenuButton.h file to your bridging header.  If you have a pure-swift project, then you may need to [create one](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html).

**Comment by zsy78191** [comment]
Thanks for loving it. and thank you @DeliciousRaspberryPi  , he is right , swift can use oc code by adding the bridging header.
