### ISSUE TITLE
Scrollable buttons

### ISSUE THREAD

**Issue by PawanmSpaceo** [zsy78191/XXXRoundMenuButton#20]
How to make buttons scrollable?

**Comment by zsy78191** [comment]
Do you mean rotary scrolling?

**Comment by PawanmSpaceo** [comment]
Yes I mean that

**Comment by zsy78191** [comment]
According to the current code design, there are some difficulties in achieving the rotation, and it is also true to realize the rolling with the fingers.

**Comment by PawanmSpaceo** [comment]
Ok, any suggestion to implement that?

**Comment by zsy78191** [comment]
If you want to implement a scrollable menu, the sliding interaction should be received by a UIScrollView. If you use a swipe gesture, you need to implement the effect of inertia deceleration. The problem with UIScrollView is that there is no way to scroll indefinitely.

My idea is
- Upper layer - UIScrollView receives touch events and forwards click events
- Middle Tier Container View - Contains all buttons, calculates the rotation angle according to ScrollView, and implements animation
- The lower layer is the container View

Use the x+y of the ScrollView's offset to calculate a detla value, which is passed to the middle layer View, which is used to rotate all the buttons.

**Comment by PawanmSpaceo** [comment]
@zsy78191 thank you, let me try it...

**Comment by zsy78191** [comment]
You are welcome
