### ISSUE TITLE
layoutDegree

### ISSUE THREAD

**Issue by pjebs** [zsy78191/XXXRoundMenuButton#3]
I understand that startDegree is where the first button object begins.
I don't quite understand layout Degree.

In your first example, it represents the angle that is the gap between the button objects.??

In the second example, there are 3 button objects and the layout degree is 90degrees?

**Comment by zsy78191** [comment]
Thanks for asking this good question.
layoutDegree is the degree between start and end.

In first demo,  start is -M_PI, the angle of layout sector is 90degrees.
![artboard 1](https://cloud.githubusercontent.com/assets/3960959/14488568/6dbbdd06-019b-11e6-8ec5-06283111924e.png)

hope to help you.

**Comment by pjebs** [comment]
The confusing part was the reference angle.
It turns out 0 degrees is at the bottom.

**Comment by zsy78191** [comment]
yeah , you are right. (:

**Comment by pjebs** [comment]
Normally the convention is 0 degrees is on the right with counter-clockwise direction being the positive direction (which you already have done)
