### ISSUE TITLE
ButtonClick in Swift

### ISSUE THREAD

**Issue by DonBaronFactory** [zsy78191/XXXRoundMenuButton#5]
Trying to call:

```
roundedButtonNavigation.buttonClickBlock { idx in
}
```

from a swift class, but the compiler rejects it with:

`Cannot call value of non-function type '((Int) -> Void)!'`

Any idea on how to call this block properly from Swift?

**Comment by zsy78191** [comment]
I already send new swift demo to answer your question. thanks .

**Comment by DonBaronFactory** [comment]
Thank you, just seen that your block is a property and not a function, thus the correct way of calling:

```
 roundedButtonNavigation.buttonClickBlock =  {(idx:NSInteger)-> Void in
            NSLog("%d", idx);
        };

```

**Comment by zsy78191** [comment]
Your welcome (:

**Comment by zsy78191** [comment]
@cre8it  Your welcome (:
