### ISSUE TITLE
Error on Iphone 4, 4s and 5

### ISSUE THREAD

**Issue by dshirazi** [zsy78191/XXXRoundMenuButton#6]
Works fine on Iphone 5s or over. On others the buttons is not distributed along axis.

![simulator screen shot jun 23 2016 2 19 02 pm](https://cloud.githubusercontent.com/assets/10730208/16312990/7f7b6d1a-394d-11e6-80f0-446a62683126.png)

**Comment by dshirazi** [comment]
On my investigations, I found diference on PI value from Iphone < 5S :0. I thought that humans already discovered the correct one.

**Comment by zsy78191** [comment]
Thanks for posting this issue. (:

**Comment by decay1969** [comment]
Printing out M_PI gives me the same number on the iPhone 5 as it does on newer devices.  @dshirazi what was your solution?

Thanks.

**Comment by dshirazi** [comment]
The issue appear to be when the M_PI is passed to func animatedLoadIcons:.

As my scenario is simple with fixed number of buttons, I edit directly on the animatedLoadIcons function with fixed value of angle and start (workaround). Even that, the start angle on Iphone <=5 is different from others, but this not affect me at this time.

Maybe this problem can occur only on IOS Simulator.

> On Jun 28, 2016, at 12:50 PM, decay1969 notifications@github.com wrote:
> 
> Printing out M_PI gives me the same number on the iPhone 5 as it does on newer devices. @dshirazi https://github.com/dshirazi what was your solution?
> 
> Thanks.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub https://github.com/zsy78191/XXXRoundMenuButton/issues/6#issuecomment-229092543, or mute the thread https://github.com/notifications/unsubscribe/AKO64GDDiVLJ7a9esJ6U023pEWCRFlO4ks5qQUKtgaJpZM4I9CmP.

Denis Shirazi
Tecnologia
- 55 11 95899 0001
  cooltours.com.br applewebdata://4CBBD0D6-5C7B-4029-AB19-7B9CE6CA7C64/%E2%80%9Chttp://www.cooltours.com.br%E2%80%9D

**Comment by rostopira** [comment]
same issue on iPhone 5c. And error not in pi, I used start 0 and layout 3 or 6 or 2, and nothing works. All icons in same place

**Comment by bizibizi** [comment]
any mews?

**Comment by bizibizi** [comment]
solution:replace CGFloat with float in your library
