### ISSUE TITLE
Data Type Inconsistency for Degree 

### ISSUE THREAD

**Issue by fatsolow88** [zsy78191/XXXRoundMenuButton#9]
Please take a look at the method which pass in the parameter for the start degree and layout degree

XXXRoundMenuButton.h
`- (void)animatedLoadIcons:(NSArray<UIImage*>*)icons start:(CGFloat)start layoutDegree:(CGFloat)layoutDegree oneByOne:(BOOL)onebyone;`

XXXRoundMenuButton.m
```
- (void)animatedLoadIcons:(NSArray<UIImage*>*)icons start:(CGFloat)start layoutDegree:(CGFloat)layoutDegree oneByOne:(BOOL)onebyone;
- (void)animatedLoadIcons:(NSArray<UIImage*>*)icons start:(double)start layoutDegree:(double)layoutDegree oneByOne:(BOOL)onebyone
```

There's inconsistency on the data type for the layoutDegree and startDegree which causes conflicting parameters types. 
It's causing issue when I try to run on iphone4/5 , the icon didn't fan out circling the center of it, but instead it stick at one location, or at the wrong location. 
When I try to nslog the layoutDegree parameter, it shows 0.000000 instead of a proper value.
But once I change the "double" to "CGFloat" , then it manage to pass in proper value for the layoutDegree and perform the animation properly.

**Comment by zsy78191** [comment]
I hope this can help you, sorry that I didn't has 4 / 5 device to fix it .

Click here https://github.com/zsy78191/XXXRoundMenuButton/issues/6

**Comment by fatsolow88** [comment]
I already did that by standardize all the data type before I see this ^_^ . But thanks.
